server:
  port: 8080
spring:
  application:
    name: delivery
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_delivery
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
  global-config:
    db-config:
      id-type: assign_id


